### ISSUE TITLE
stratum_recv_line failed / Stratum connection interrupted

### ISSUE THREAD

**Issue by AmiT177** [pooler/cpuminer#124]
Hey,
No matter on what pool I'm mining,
I'm getting this error.
"stratum_recv_line failed"
"Stratum connection interrupted"

OS: Ubuntu 16.04
Current pool: F2Pool

**Comment by pooler** [comment]
Please provide more information. Which version of cpuminer? Did you build it yourself? If not, where did you get the binary? What parameters are you passing? Does the error pop up immediately after you start the miner or after some time?

**Comment by LinhDart** [comment]
@pooler Mee too, I'm using ubuntu 17.x I've build by myself. But when i use cpumier of JayDDee, everything is ok.

**Comment by AmiT177** [comment]
Version 2.5.0,
Build it using the build instruction,
Parameters: "-a sha256d --url --userpass"
pops after some time

**Comment by pooler** [comment]
This looks like an issue with the server or with the network connection, not with the miner.
Could you provide detailed instructions to reproduce it? Please do not omit the address of the server, it is relevant.

**Comment by Linkin87** [comment]
i dont think so, there are many pepple like me and they change to use another tool.

**Comment by AmiT177** [comment]
I changed alot of pools, all of them has the same problem,

"./minerd -a sha256d --url=stratum+tcp://<link>:3333 -userpass=<username>_<worker>:<pass>"
Thats how I start it.

Also, is it not supposed to say accepted or something?

**Comment by pooler** [comment]
Again, please provide one pool address where you can consistently reproduce this issue, so that I can try to reproduce it myself.

> Also, is it not supposed to say accepted or something?

Sure, but if you're mining Bitcoin finding a share can take a really long time.

**Comment by AmiT177** [comment]
My fault, eu1.bitminter.com:3333

**Comment by pooler** [comment]
After running cpuminer against eu1.bitminter.com:3333 for two hours, what I observed is that the server interrupts the connection every 11 minutes exactly. This is clearly a timeout to disconnect clients that appear to be inactive (not submitting any shares).
There doesn't appear to be anything wrong with the miner or the server, they're both behaving as expected. The server simply disconnects you because you're not submitting any shares, you're not finding any shares because you're extremely slow relative to the difficulty that the server sets, and the difficulty is set so high because the server is not expecting anyone to mine with a CPU.

@Linkin87: just for the sake of completeness I also tested the fork you mentioned, and it exhibits the exact same behavior.

**Comment by AmiT177** [comment]
uh, okay thank you!
do you have any pools that has low difficulty? or its not the right place?

**Comment by pooler** [comment]
This is not the right place to ask, but if you want my opinion, you shouldn't be mining Bitcoin with CPUs at all.

**Comment by calidion** [comment]
i am encountering the same problem.

**Comment by lordvalium** [comment]
me too

**Comment by usscsmith** [comment]
I'm brand new to mining and still trying to digest even the basics... But I've been playing with Awesome Miner while I figure everything out and I started a new miner and kept seeing with every profit pool.

Turns out it did not like my BTC Wallet address... When I changes the Wallet address to my NiceHash and restarted the miner; it had no issues.

**Comment by leshacat** [comment]
I have same issue, from sounds of this discussion it is likely server-side.

@pooler is right about the timeout, makes perfect sense. I have noticed this only on my smaller miners who I also noticed don't submit shares as often. I assume it just reconnects and sends any shares afterwards.

The thing you should be concerned with is if it says "Boooo!" thats when it rejected a share.

**Comment by g4o2** [comment]
yyyyyyoooooooooooooooooooooo
