### ISSUE TITLE
Mined block gives "bad-txnmrklroot" error

### ISSUE THREAD

**Issue by Re0h** [pooler/cpuminer#166]
I am solo mining using sha256d (on testnet), on both Ubuntu 16.04 and Windows 10. Compiled the source code, and using bitcoind's RPC server using getblocktemplate. Whenever a block is found, bitcoind responds with "bad-txnmrklroot". I use the following command to start the miner:

./minerd -q -D -a sha256d -o [bitcoind address/port] -O username:password --coinbase-addr=[address]

Am I messing something up, or is this a bug?

**Comment by pooler** [comment]
Is this with an unmodified Bitcoin Core 0.16? I tried to replicate what you describe, but the difficulty on testnet is impossibly high for a CPU, and even with the 20-minute rule the window for finding a block is rather small. I'm wondering if you are doing anything special that you didn't mention?

**Comment by Re0h** [comment]
The block template was provided by a [gocoin](https://github.com/piotrnar/gocoin)) node. I submitted the mined block to an unmodified Bitcoin Core (0.16) using the bitcoin-cli, which complained about the merkle root. I contacted the author of gocoin about my issue and he told me it was most likely a problem with the mining software I use. I tried mining with a bitcoin core node, but was unable to get any blocks at all. At this point I do not know for sure whether this is an issue with cpuminer or with the getblocktemplate RPC from gocoin, so maybe I should continue this discussion on the bitcoin-talk forum (if so, feel free to close this issue).

**Comment by pooler** [comment]
Could you post one of the block templates that led to an invalid block?

**Comment by Re0h** [comment]
I don't have one of the block templates that resulted in an invalid block saved, but here is a typical block template from gocoin: https://pastebin.com/KZ5D3KPQ

**Comment by pooler** [comment]
The block template you posted does not seem to be compliant with [BIP145](https://github.com/bitcoin/bips/blob/master/bip-0145.mediawiki), because:

- _Transactions with witness data may only be included if the template's "rules" list (see BIP 9) includes "segwit"._ — This template has segwit transactions, but no "rules" list.
- _When witness transactions are included in the block, the primary merkle root MUST be calculated with those transactions' "txid" field instead of "hash"._ — This template does not provide a "txid" field for any of its segwit transactions. It does provide the required value, but calls it "hash" instead, which BIP145 defines as _reversed hash of complete transaction (with witness data included)_, a very different thing in the case of a segwit transaction.

Why could this template work with other mining software, but not with cpuminer? Since [BIP22](https://github.com/bitcoin/bips/blob/master/bip-0022.mediawiki) does not require a "hash" field to be present, cpuminer always ignores it in the case of templates not specifying the "segwit" rule, and simply computes the hash of "data" from scratch. Other mining software may use the "hash" field when present for such templates, and that would lead to the same result if the input conformed to the specification.

I'd suggest reporting this issue to the author of the software that produced the template in question.

**Comment by Re0h** [comment]
Thank you for looking into this, I will report your findings to the author of gocoin.
