### ISSUE TITLE
No support for Bech32 addresses

### ISSUE THREAD

**Issue by AdeBlanche** [pooler/cpuminer#174]
When i set "coinbase-addr" to a bech32 address (address starting with bc1) i get the error message: 
> minerd: invalid address -- 'bc1qc07c4qsx9sc73pv2xld46u28l6zea6epazsn0u'

**Comment by vereen-cf** [comment]
You can use [http://cryptocurrencytools.org/](url) to convert your private key into a bech32 address and a legacy address. Remember to download the GitHub repo and go offline before entering your private key!

**Comment by kerberosxyz** [comment]
With Litecoin, following issue occurs:
- When starting the Litecoin Core (0.16.3) wallet with the parameter "-addresstype=legacy", it generates traditional "L" addresses and you can mine to it with minerd.
- When starting the wallet with "-addresstype=p2sh-segwit" (which is in fact the default if you don't specify the address type), it generates "M" addresses. You can mine to this address with minerd, but when finding a block it does not give you any reward.
- Finally, if you start the wallet with -addresstype=bech32, it generates "ltc1" addresses. When you try to mine to this address type, you get indeed the error "./minerd: invalid address"

Is there any plan to add segwit support to minerd?

**Comment by pooler** [comment]
> When starting the wallet with "-addresstype=p2sh-segwit" (which is in fact the default if you don't specify the address type), it generates "M" addresses. You can mine to this address with minerd, but when finding a block it does not give you any reward.

That's because cpuminer interprets such an address differently from a standard Litecoin client. cpuminer currently interprets all addresses as P2PKH, except for addresses with a version of 5 or 196 (Bitcoin's P2SH versions for mainnet and testnet, respectively), which are interpreted as P2SH. Litecoin also used to use version 5 (i.e. address starts with '3') for mainnet P2SH addresses, but in 2017 it switched to version 50 (i.e. address starts with 'M') to differentiate itself from Bitcoin.
If you use [this tool](https://litecoin-project.github.io/p2sh-convert/) to convert your P2SH address starting with 'M' to its legacy format starting with '3', everything should work.

The reason why version 50 is not automatically recognized as P2SH is that other cryptocurrencies (e.g. Myriad) use this version number for their P2PKH addresses. The proper way to handle this conflict would probably be to add command-line flags to cpuminer so that one can explicitly state the type of the provided address.

> Is there any plan to add segwit support to minerd?

I'm not making any promises, but I'll give it a shot if time allows.

**Comment by pooler** [comment]
Support for bech32 addresses added in 7e89602.

**Comment by kerberosxyz** [comment]
> Support for bech32 addresses added in [7e89602](https://github.com/pooler/cpuminer/commit/7e8960212f0055d6dafaa3c80812c50cec291de3).

Thanks alot for this update! I can now indeed mine to native segwit addreses.

**Comment by Jolly-Pirate** [comment]
Can you add support for P2SH too?
