### ISSUE TITLE
Questions.

### ISSUE THREAD

**Issue by thiago1255** [pooler/cpuminer#217]
hello, I have two questions.  is there any tuturial that teaches how to use it? Can I mine dogecoin solo with this miner? Thanks.

**Comment by juanpc2018** [comment]
#1. 
in terminal type:
c:/cpuminer folder/>cpuminer --help
or -?

#2.  DOGEcoin has the same algoritm as LiteCoin, scrypt
long ago was discovered that both coins could be mined simultaneously with same Hash and HW,

that gives robustness to DOGEcoin, but also more difficulty for mining...

mining solo today is almost impossible because the difficulty level.
some people Hire/Rent large clusters to mine "solo", like nicehashminer
and mine in a large pool, eating all the small miners,
https://miningpoolstats.stream/dogecoin

most softwares that are based on BitCoin have similar modifications,
one of those modifications was to remove solo CPU mining from the Wallet code.

developers claim it was useless / outdated...because difficulty
but Original Satoshi Nalamoto wallet code used solo CPU mining to send without fee from a Node Wallet,...

Bitcoin developers do Not follow or understand Satoshi Nalamoto original vision / ideas....
and all coins based on Bitcoin, follow the same modifications like a waterfall / domino effect....
Bitcoin-->Litecoin-->DOGEcoin

sometimes developers do Not agree, and thats where a Friendly Fork is done...
for example:
LiteCoin was the 1st forked version of Bitcoin, resetting from 0 the block chain, with a different algorithm,
Scrypt instead of SHA256d

Ethereum Classic and Ethereum waere the 1st fork for that coin technology, but 2nd major coin fork in the eCoin ecosystem.

Bitcoin Chash, Bitcoin Gold, Bitcoin Diamond BCD, SV, etc...
all were more forks of Bitcoin original blockchain, Not resetting the Blockchain, and usually changeing the algorithm, the block size, the max available coins, or any other specification...

Bytecoin was the 1st coin with Cryptonight algo a different technology, 
XMR Monero was a fork of Bytecoin BCN, and XMR had many changes in the code & algorithms, 
BCN had No changes.

etc....  
last year or more was found a way to translate DOGEcoins to Ethereum Tokens, if i remember correctly, there was a very big reward for the code...
Ethereum is a virtual machine that can run other codes inside it, mostly used for other sub-coins, or smart contracts.

short answere is No,
Most Node Wallet coins software cannot be mined with external nor internal miner, the code was removed, 
only pools have a modified Node Wallet that can be mined externally...
there are different protocols, getblocktemplate, etc..
that gives the Network a weak spot.
 achiles heel....
there are very few pools, if pools Die, the coin dies.
original Satpshi Nakamoto idea was that every Node/wallet could mine to make the coin failsafe.
to avoid centralization, like alexasndria library fire..
coins are going the wrong way if you ask me...

**Comment by pooler** [comment]
This is an issue tracker, not a support forum.
